service: serverless-schedule-example
frameworkVersion: '3'
useDotenv: true
package:
  individually: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  profile: ${opt:aws-profile, env:AWS_PROFILE, ''}
  stage: ${opt:stage, env:STAGE, 'local'}
  region: ${opt:region, env:AWS_REGION, 'us-east-1'}

functions:
  cronJob:
    handler: cron-handler.hello
    events:
      - schedule: ${env:CRON_SCHEDULE, 'cron(*/5 * ? * * *)'}
