service: ${env:SERVICE_NAME, 'StartStopEC2Instance'}
frameworkVersion: '3'
package:
  individually: true
plugins:
  - serverless-offline
  - serverless-python-requirements

useDotenv: true

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, env:STAGE, 'local'}
  region: ${opt:region, env:AWS_REGION, 'us-east-1'}
  profile: ${opt:aws-profile, env:AWS_PROFILE, ''}
  deploymentBucket:
    blockPublicAccess: true
    versioning: true
    serverSideEncryption: AES256
  iamRoleStatements:
    - Effect: Allow # Check if needed
      Action:
        - ec2:DescribeInstanceStatus
        - ec2:DescribeInstances
      Resource:
        - "*"
    - Effect: Allow
      Action:
        - ec2:StartInstances
        - ec2:StopInstances
      Resource:
        - Fn::Join:
            - ":"
            - - "arn:aws:ec2"
              - Ref: AWS::Region
              - Ref: AWS::AccountId
              - "instance/*"

functions:
  startInstance:
    handler: src/handlers/start.handler
    events:
      - schedule: ${env:START_INSTANCE, 'cron(0 0 * * ? *)'}
  stopInstance:
    handler: src/handlers/stop.handler
    events:
      - schedule: ${env:STOP_INSTANCE, 'cron(0 0 * * ? *)'}

