service: azfx-http-example
frameworkVersion: '3'

provider:
  name: azure
  region: ${opt:region, env:REGION, 'West US 2'}
  runtime: nodejs14
  stage: ${opt:stage, 'local'}
  # os: windows  # windows is default, linux is available
  # prefix: "sample"  # prefix of generated resource name
  # subscriptionId: A356AC8C-E310-44F4-BF85-C7F29044AF99
  # type: premium  # premium azure functions

  environment:
    VARIABLE_FOO: 'foo'

plugins:
  - serverless-azure-functions

functions:
  hello:
    handler: src/handlers/hello.sayHello
    events:
      - http: true
        methods:
          - GET
        authLevel: anonymous # can also be `function` or `admin`

  goodbye:
    handler: src/handlers/goodbye.sayGoodbye
    events:
      - http: true
        methods:
          - GET
        authLevel: anonymous
